### ISSUE TITLE
计算令牌数取整

### ISSUE THREAD

**Issue by HxmLi** [2388386839/syj-ratelimit#1]
计算令牌数的时候需要取整，否则lua脚本里面的数值计算都是浮点计算，会导致令牌数出现小数，从而redis执行减一的时候报错。
需要修改的代码行  
local maxValue = value+diff/interval*step;
修改为:
local maxValue = math.floor(value+diff/interval*step);
会报错的代码行
 redis.call('DECR',key);

**Comment by HxmLi** [comment]
生产环境的redis一般为集群部署的，建议修改为可适用于集群部署。
当集群部署的时候lua脚本参数的所有key和脚本里面的key需要具有相同的slot，以使所有命令都分发到同一个redis服务器上才可以，否则会导致限流失败。

**Comment by 2388386839** [comment]
value+ math.floor(diff/interval)*step;
这样加效果更好。哈哈！
