### ISSUE TITLE
TokenBucketAlgorithmImpl这个类里面的rateLimiter这个对象是怎么注入进去的

### ISSUE THREAD

**Issue by mrsWangxing** [2388386839/syj-ratelimit#5]
我下载到源码后 必须在rateLimiter这个变量上加@Autowired这个注解才能注册进去值 否则 打印出来rateLimiter为空 
是我的环境的问题？还是框架有问题呢？

**Comment by 2388386839** [comment]
> 
> 
> 我下载到源码后 必须在rateLimiter这个变量上加@Autowired这个注解才能注册进去值 否则 打印出来rateLimiter为空
> 是我的环境的问题？还是框架有问题呢？

有没有增加启动注解@EnableSyjRateLimit呢，如果增加了启动注解的话会在EnableSyjRateLimitConfiguration这个类里面自动装配的

**Comment by mrsWangxing** [comment]
@EnableSyjRateLimit 这个注解加了 
EnableSyjRateLimitConfiguration这个类确实会在spring容器中放入 一个RateLimiter类型的对象 
但是 在 TokenBucketAlgorithmImpl 这个类里面 的 rateLimiter 这个属性 没有@Autowired 在consume方法中用的时候 会报空指针异常 
假如不加这个注解 @Autowired  ；是什么原理把rateLimiter 注入到TokenBucketAlgorithmImpl 这个类里面的呢

**Comment by 2388386839** [comment]
> @EnableSyjRateLimit 这个注解加了
> EnableSyjRateLimitConfiguration这个类确实会在spring容器中放入 一个RateLimiter类型的对象
> 但是 在 TokenBucketAlgorithmImpl 这个类里面 的 rateLimiter 这个属性 没有@Autowired 在consume方法中用的时候 会报空指针异常
> 假如不加这个注解 @Autowired ；是什么原理把rateLimiter 注入到TokenBucketAlgorithmImpl 这个类里面的呢

这个对象注入主要是使用了Lombok插件的@RequiredArgsConstructor，这个注解为类提供了一个包含带有@NonNull注解变量的构造方法，Spring在执行时就会自动把这些变量注入进去。你的情况可能是因为本地开发工具没有集成Lombok的原因。可以选择使用maven中央仓库的依赖或者开发工具增加Lombok集成环境

**Comment by mrsWangxing** [comment]
嗯  应该是这个原因
