### ISSUE TITLE
令牌通算法脚本的BUG

### ISSUE THREAD

**Issue by sail-y** [2388386839/syj-ratelimit#6]
```lua
if  diff > interval 
```

经过测试发现，在令牌通算法并发情况下，接口耗时1秒，并发20，设置令牌刷新时间1秒，令牌数量20，如果第一秒花光令牌，那么第二秒的时候请求过来`diff`应该是1，但是`interval`也是1，所以在这一秒中，所有的请求都无法拿到令牌

**Comment by 2388386839** [comment]
> diff



> ```lua
> if  diff > interval 
> ```
> 
> 经过测试发现，在令牌通算法并发情况下，接口耗时1秒，并发20，设置令牌刷新时间1秒，令牌数量20，如果第一秒花光令牌，那么第二秒的时候请求过来`diff`应该是1，但是`interval`也是1，所以在这一秒中，所有的请求都无法拿到令牌

确实是有这个问题
